[package]
name = "zk_stark"
version = "0.1.0"
edition = "2021"

[dependencies]
curve25519-dalek = { version = "4.1.3" }
rand = { version = "0.8.5" }
rpassword = { version = "7.3.1" }
sha2 = { version = "0.10.8" }